### ISSUE TITLE
Healthcare Clinic: Kanban Board Setup

### ISSUE THREAD

**Issue by mahdinoori2000** [mahdinoori2000/healthcare-app-backend#19]
- [ ] We are 3 in our goup:

- [Mahdi Noori](@mahdinoori2000)
- [Mayito Ismail](@ismayito)
- [Uzair Manzoor](@Uzair-Manzoor)

- [ ] This is the link for the kanban board:

- https://github.com/mahdinoori2000/healthcare-app-backend/projects/1

- [ ] This is the screenshot of the Kanban Board

![image](https://github.com/mahdinoori2000/healthcare-app-backend/assets/126486418/b9a13325-75f1-4288-8554-c4191e3654c5)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
